// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn2vYwQwDJocTqLD6NpXrPxSr_yNX_bOU',
    appId: '1:599222127574:android:34ac1604b93f6a03a93277',
    messagingSenderId: '599222127574',
    projectId: 'extension-vendor',
    databaseURL: 'https://extension-vendor-default-rtdb.firebaseio.com',
    storageBucket: 'extension-vendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQB3SH4O-oMYL7BaYVSs6XP0g0SIz4e0',
    appId: '1:599222127574:ios:f96de2eaa32de9d5a93277',
    messagingSenderId: '599222127574',
    projectId: 'extension-vendor',
    databaseURL: 'https://extension-vendor-default-rtdb.firebaseio.com',
    storageBucket: 'extension-vendor.appspot.com',
    iosClientId: '599222127574-n42jd80r9p6hpsr8lnnntnvu5oumrag3.apps.googleusercontent.com',
    iosBundleId: 'com.badee.exvendor',
  );
}
